name: Unit Tests
on:
  pull_request:
    branches:
      - main
jobs:
  UnitTests: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        run: echo "Repositoy ${{ github.repository }} has been checked out"
      - name: testing secrets 
        run: echo ${{ secrets }}
